export const FETCH_FILMMAKERS = 'FETCH_FILMMAKERS';
export const RECEIVED_FILMMAKERS = 'RECEIVE_FILMMAKERS_SUCCEEDED';
export const FAILED_FILMMAKERS = 'RECEIVE_FILMMAKERS_FAILED';

export const FETCH_PROGRAMS = 'FETCH_PROGRAMS';
export const RECEIVED_PROGRAMS = 'RECEIVE_PROGRAMS_SUCCEEDED';
export const FAILED_PROGRAMS = 'RECEIVE_PROGRAMS_FAILED';

export const FETCH_FILMS = 'FETCH_FILMS';
export const RECEIVED_FILMS = 'RECEIVE_FILMS_SUCCEEDED';
export const FAILED_FILMS = 'RECEIVE_FILMS_FAILED';

export const FETCH_ITEM = 'FETCH_ITEM';
export const RECEIVED_ITEM = 'RECEIVE_ITEM_SUCCEEDED';
export const FAILED_ITEM = 'RECEIVE_ITEM_FAILED';

export const FETCH_ITEMS = 'FETCH_ITEMS';
export const RECEIVED_ITEMS = 'RECEIVE_ITEMS_SUCCEEDED';
export const FAILED_ITEMS = 'RECEIVE_ITEMS_FAILED';

export const ADD_ITEM_MENU_HEADER = 'ADD_ITEM_MENU_HEADER';
export const RESET_ITEM_MENU_HEADERS = 'RESET_ITEM_MENU_HEADERS';

export const OPEN_SORT = 'OPEN_SORT';
export const CLOSE_SORT = 'CLOSE_SORT';
export const REINITIALIZE_SORT = 'REINITIALIZE_SORT';
export const SET_ACTION_SORT_OPTION = 'SET_ACTION_SORT_OPTION';