export const FETCH_FILMMAKERS = 'FETCH_FILMMAKERS';
export const RECEIVED_FILMMAKERS = 'RECEIVED_FILMMAKERS';
export const FAILED_FILMMAKERS = 'FAILED_FILMMAKERS';

export const FETCH_PROGRAMS = 'FETCH_PROGRAMS';
export const RECEIVED_PROGRAMS = 'RECEIVED_PROGRAMS';
export const FAILED_PROGRAMS = 'FAILED_PROGRAMS';

export const FETCH_FILMS = 'FETCH_FILMS';
export const RECEIVED_FILMS = 'RECEIVED_FILMS';
export const FAILED_FILMS = 'FAILED_FILMS';

export const FETCH_ITEM = 'FETCH_ITEM';
export const RECEIVED_ITEM = 'RECEIVED_ITEM';
export const FAILED_ITEM = 'FAILED_ITEM';

export const FETCH_ITEM_FILMMAKER = 'FETCH_ITEM_FILMMAKER';
export const RECEIVED_ITEM_FILMMAKER = 'RECEIVED_ITEM_FILMMAKER';
export const FAILED_ITEM_FILMMAKER = 'FAILED_ITEM_FILMMAKER';

export const FETCH_ITEM_FILMMAKER_FILMS = 'FETCH_ITEM_FILMMAKER_FILMS';
export const RECEIVED_ITEM_FILMMAKER_FILMS = 'RECEIVED_ITEM_FILMMAKER_FILMS';
export const FAILED_ITEM_FILMMAKER_FILMS = 'FAILED_ITEM_FILMMAKER_FILMS';

export const FETCH_ITEM_FILMS = 'FETCH_ITEM_FILMS';
export const RECEIVED_ITEM_FILMS = 'RECEIVED_ITEM_FILMS';
export const FAILED_ITEM_FILMS = 'FAILED_ITEM_FILMS';

export const FETCH_ITEMS = 'FETCH_ITEMS';
export const RECEIVED_ITEMS = 'RECEIVED_ITEMS';
export const FAILED_ITEMS = 'FAILED_ITEMS';

export const ADD_ITEM_MENU_HEADER = 'ADD_ITEM_MENU_HEADER';
export const RESET_ITEM_MENU_HEADERS = 'RESET_ITEM_MENU_HEADERS';

export const OPEN_SORT = 'OPEN_SORT';
export const CLOSE_SORT = 'CLOSE_SORT';
export const REINITIALIZE_SORT = 'REINITIALIZE_SORT';
export const SET_ACTION_SORT_OPTION = 'SET_ACTION_SORT_OPTION';

export const FIND_TYPEAHEAD_CHOICES = 'FIND_TYPEAHEAD_CHOICES';

export const FETCH_CHOICES = 'FETCH_CHOICES';
export const RECEIVED_CHOICES = 'RECEIVED_CHOICES';
export const FAILED_CHOICES = 'FAILED_CHOICES';

export const FETCH_EVENTS = 'FETCH_EVENTS';
export const RECEIVED_EVENTS = 'RECEIVED_EVENTS';
export const FAILED_EVENTS = 'FAILED_EVENTS';

export const FETCH_NEWS = 'FETCH_NEWS';
export const RECEIVED_NEWS = 'RECEIVED_NEWS';
export const FAILED_NEWS = 'FAILED_NEWS';

export const FETCH_POSTS = 'FETCH_POSTS';
export const RECEIVED_POSTS = 'RECEIVED_POSTS';
export const FAILED_POSTS = 'FAILED_POSTS';

export const FETCH_EPHEMERA = 'FETCH_EPHEMERA';
export const RECEIVED_EPHEMERA = 'RECEIVED_EPHEMERA';
export const FAILED_EPHEMERA = 'FAILED_EPHEMERA';

export const FETCH_SPOTLIGHT = 'FETCH_SPOTLIGHT';
export const RECEIVED_SPOTLIGHT = 'RECEIVED_SPOTLIGHT';
export const FAILED_SPOTLIGHT = 'FAILED_SPOTLIGHT';

export const FETCH_ITEM_MEDIA = 'FETCH_ITEM_MEDIA';
export const RECEIVED_ITEM_MEDIA = 'RECEIVED_ITEM_MEDIA';
export const FAILED_ITEM_MEDIA = 'FAILED_ITEM_MEDIA';

export const FETCH_ITEMS_MEDIA = 'FETCH_ITEMS_MEDIA';
export const RECEIVED_ITEMS_MEDIA = 'RECEIVED_ITEMS_MEDIA';
export const FAILED_ITEMS_MEDIA = 'FAILED_ITEMS_MEDIA';
