export const FETCH_FILMMAKERS = 'FETCH_FILMMAKERS';
export const RECEIVED_FILMMAKERS = 'RECEIVED_FILMMAKERS';
export const FAILED_FILMMAKERS = 'FAILED_FILMMAKERS';

export const FETCH_PROGRAMS = 'FETCH_PROGRAMS';
export const RECEIVED_PROGRAMS = 'RECEIVED_PROGRAMS';
export const FAILED_PROGRAMS = 'FAILED_PROGRAMS';
export const RECEIVED_PROGRAM_MEDIA = 'RECEIVED_PROGRAM_MEDIA';

export const FETCH_FILMS = 'FETCH_FILMS';
export const RECEIVED_FILMS = 'RECEIVED_FILMS';
export const FAILED_FILMS = 'FAILED_FILMS';

export const FETCH_ITEM = 'FETCH_ITEM';
export const RECEIVED_ITEM = 'RECEIVED_ITEM';
export const FAILED_ITEM = 'FAILED_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';

export const FETCH_ITEM_FILMMAKER = 'FETCH_ITEM_FILMMAKER';
export const RECEIVED_ITEM_FILMMAKER = 'RECEIVED_ITEM_FILMMAKER';
export const FAILED_ITEM_FILMMAKER = 'FAILED_ITEM_FILMMAKER';

export const FETCH_ITEM_FILMMAKER_FILMS = 'FETCH_ITEM_FILMMAKER_FILMS';
export const RECEIVED_ITEM_FILMMAKER_FILMS = 'RECEIVED_ITEM_FILMMAKER_FILMS';
export const FAILED_ITEM_FILMMAKER_FILMS = 'FAILED_ITEM_FILMMAKER_FILMS';

export const FETCH_ITEM_FILMS = 'FETCH_ITEM_FILMS';
export const RECEIVED_ITEM_FILMS = 'RECEIVED_ITEM_FILMS';
export const FAILED_ITEM_FILMS = 'FAILED_ITEM_FILMS';

export const FETCH_ITEMS = 'FETCH_ITEMS';
export const RECEIVED_ITEMS = 'RECEIVED_ITEMS';
export const FAILED_ITEMS = 'FAILED_ITEMS';

export const ADD_ITEM_MENU_HEADER = 'ADD_ITEM_MENU_HEADER';
export const RESET_ITEM_MENU_HEADERS = 'RESET_ITEM_MENU_HEADERS';

export const OPEN_SORT = 'OPEN_SORT';
export const CLOSE_SORT = 'CLOSE_SORT';
export const REINITIALIZE_SORT = 'REINITIALIZE_SORT';
export const SET_ACTION_SORT_OPTION = 'SET_ACTION_SORT_OPTION';

export const FIND_TYPEAHEAD_CHOICES = 'FIND_TYPEAHEAD_CHOICES';

export const FETCH_CHOICES = 'FETCH_CHOICES';
export const RECEIVED_CHOICES = 'RECEIVED_CHOICES';
export const FAILED_CHOICES = 'FAILED_CHOICES';

export const FETCH_EVENTS = 'FETCH_EVENTS';
export const RECEIVED_EVENTS = 'RECEIVED_EVENTS';
export const FAILED_EVENTS = 'FAILED_EVENTS';
export const RECEIVED_EVENT_MEDIA = 'RECEIVED_EVENT_MEDIA';

export const FETCH_EVENT_DETAIL = 'FETCH_EVENT_DETAIL';
export const RECEIVED_EVENT_DETAIL = 'RECEIVED_EVENT_DETAIL';
export const FAILED_EVENT_DETAIL = 'FAILED_EVENT_DETAIL';

export const FETCH_EVENT_DETAIL_FILMS = 'FETCH_EVENT_DETAIL_FILMS';
export const RECEIVED_EVENT_DETAIL_FILM = 'RECEIVED_EVENT_DETAIL_FILM';
export const FAILED_EVENT_DETAIL_FILM = 'FAILED_EVENT_DETAIL_FILM';
export const FAILED_EVENT_DETAIL_FILMS = 'FAILED_EVENT_DETAIL_FILMS';

export const FETCH_NEWS = 'FETCH_NEWS';
export const RECEIVED_NEWS = 'RECEIVED_NEWS';
export const FAILED_NEWS = 'FAILED_NEWS';

export const FETCH_NEWS_DETAIL = 'FETCH_NEWS_DETAIL';
export const RECEIVED_NEWS_DETAIL = 'RECEIVED_NEWS_DETAIL';
export const FAILED_NEWS_DETAIL = 'FAILED_NEWS_DETAIL';

export const FETCH_POSTS = 'FETCH_POSTS';
export const RECEIVED_POSTS = 'RECEIVED_POSTS';
export const FAILED_POSTS = 'FAILED_POSTS';

export const FETCH_EPHEMERA = 'FETCH_EPHEMERA';
export const RECEIVED_EPHEMERA = 'RECEIVED_EPHEMERA';
export const FAILED_EPHEMERA = 'FAILED_EPHEMERA';

export const FETCH_SPOTLIGHT = 'FETCH_SPOTLIGHT';
export const RECEIVED_SPOTLIGHT = 'RECEIVED_SPOTLIGHT';
export const FAILED_SPOTLIGHT = 'FAILED_SPOTLIGHT';

export const FETCH_SPOTLIGHT_ITEM_DATA = 'FETCH_SPOTLIGHT_ITEM_DATA';
export const RECEIVED_SPOTLIGHT_ITEM_DATA = 'RECEIVED_SPOTLIGHT_ITEM_DATA';
export const FAILED_SPOTLIGHT_ITEM_DATA = 'FAILED_SPOTLIGHT_ITEM_DATA';

export const FETCH_ITEM_MEDIA = 'FETCH_ITEM_MEDIA';
export const RECEIVED_ITEM_MEDIA = 'RECEIVED_ITEM_MEDIA';
export const FAILED_ITEM_MEDIA = 'FAILED_ITEM_MEDIA';

export const FETCH_ITEMS_MEDIA = 'FETCH_ITEMS_MEDIA';
export const RECEIVED_ITEMS_MEDIA = 'RECEIVED_ITEMS_MEDIA';
export const FAILED_ITEMS_MEDIA = 'FAILED_ITEMS_MEDIA';

export const FETCH_SEARCHED_ITEMS = 'FETCH_SEARCHED_ITEMS';
export const RECEIVED_SEARCHED_ITEMS = 'RECEIVED_SEARCHED_ITEMS';
export const FAILED_SEARCHED_ITEMS = 'FAILED_SEARCHED_ITEMS';

export const FETCH_FILMMAKERS_MEDIA = 'FETCH_FILMMAKERS_MEDIA';
export const RECEIVED_FILMMAKERS_MEDIA = 'RECEIVED_FILMMAKERS_MEDIA';
export const FAILED_FILMMAKERS_MEDIA = 'FAILED_FILMMAKERS_MEDIA';

export const FETCH_FILMMAKER_AVATAR = 'FETCH_FILMMAKER_AVATAR';
export const RECEIVED_FILMMAKER_AVATAR = 'RECEIVED_FILMMAKER_AVATAR';
export const FAILED_FILMMAKER_AVATAR = 'FAILED_FILMMAKER_AVATAR';

export const SHOW_FULL_SIZED_CAROUSEL = 'SHOW_FULL_SIZED_CAROUSEL';
export const OFFSET_FULL_SIZED_CAROUSEL_PHOTO = 'OFFSET_FULL_SIZED_CAROUSEL_PHOTO';
export const SET_FULL_SIZED_CAROUSEL_PHOTO = 'SET_FULL_SIZED_CAROUSEL_PHOTO';
export const HIDE_FULL_SIZED_CAROUSEL = 'HIDE_FULL_SIZED_CAROUSEL';
export const SET_FULL_SIZED_CAROUSEL_ITEM_ASPECT = 'SET_FULL_SIZED_CAROUSEL_ITEM_ASPECT';